POST http://192.168.1.106:4000/api/carta
Content-Type: application/json

{
    "imagen":"images/costeña.png",
    "producto": "Duff",
    "volumen": "300 ml",
    "valor": 3300,
    "id_tipo": 2
    } 
###
